apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dnsentries.kuberth.io
spec:
  group: kuberth.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: dnsentries
    singular: dnsentry
    kind: DnsEntry
    shortNames:
    - dns
    - de