apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
    name: kuberth
initializers:
    - name: ingress.initializer.kuberth.io
      rules:
      - apiGroups:
        - "*"
        apiVersions:
        - "*"
        resources:
        - ingresses
